FROM debian:jessie

RUN apt-get update

RUN apt-get install -y  libssl-dev libssh-dev libidn11-dev libpcre3-dev libgtk2.0-dev libmysqlclient-dev libpq-dev libsvn-dev firebird2.1-dev libncp-dev telnet hydra

